export const queryKeys = {
  user: 'user',
  product: 'product',
  token: 'token',
  newToken: 'newToken',
  allEvent: 'allEvent',
  event: 'event',
  allNotice: 'allNotice',
  cart: 'cart',
  productDetails: 'productDetails',
  favorite: 'favorite',
  review: 'review',
  coupon: 'coupon',
  newProduct: 'newProduct',
  banner: 'banner',
  productDetailsPeriod: 'productDetailsPeriod',
  productDetailsColor: 'productDetailsColor',
  productDetailsGraphic: 'productDetailsGraphic',
  productDetailsAll: 'productDetailsAll',
  filterList: 'filterList',
  recommend: 'recommend',
  noticeDetail: 'noticeDetail'
}
